### ISSUE TITLE
context.drawImage is not a function

### ISSUE THREAD

**Issue by eard7** [node-3d/webgl-raub#3] opened 2018-10-31 21:42 UTC
Hi Raub! Thank you so much for your great work here.
I'm reaching to you because i have noticed an error.  When the texture is not Pow of 2, this error is being triggered:
```$ node crate.js
THREE.WebGLRenderer 89
C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:18538
                                context.drawImage( image, 0, 0, canvas.width, canvas.height );
                                        ^

TypeError: context.drawImage is not a function
    at makePowerOfTwo (C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:18538:13)
    at uploadTexture (C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:18917:13)
    at WebGLTextures.setTexture2D (C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:18699:6)
    at WebGLRenderer.setTexture2D (C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:23541:14)
    at SingleUniform.setValueT1 [as setValue] (C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:4937:12)
    at Function.WebGLUniforms.upload (C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:5278:7)
    at setProgram (C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:23088:19)
    at WebGLRenderer.renderBufferDirect (C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:21873:18)
    at renderObject (C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:22632:11)
    at renderObjects (C:\Users\elmer\Repos\3d-core-raub\node_modules\node-threejs-raub\build\three.js:22603:6)
```

I was going to add this bug on the 3d-core-raub repo but after some debugging i noticed the error is on this package. Looks like the context (webgl) doesn't have the drawImage function, and after reviewing the code looks like its actually true. We can easily replicate this error by changing the dimensions of the crate.gif file and run the crate example.

Do you have a workaround for this issue?

Thanks, really appreciate the work.

**Comment by raub** [comment] 2018-11-03 10:33
Hi! Well, I've seen this one.

Ok, this works as follows: GL wants your texture to be pow2 and threejs for that matter creates a temporary 2d context (not WebGL!) and draws it there for stretching. Then the captured pow2 texture is fed into GL instead of the original. See `makePowerOfTwo( image )` [here](https://raw.githubusercontent.com/mrdoob/three.js/dev/build/three.js).

The shortest workaround yet, is to stretch your original image manually. After all, GL is made to work with pow2 textures.

To fix this behavior completely we have to:
1. Override `canvas.getContext` for the special '2d' case.
2. Provide some intermediate object which is able to:
  a. "Draw/stretch" an image as in `context.drawImage( image, 0, 0, _canvas.width, _canvas.height )`.
  b. Mimic the Image behavior when passed to `gl.texImage2D`
  c. Probably the best candidate is [Image itself](https://github.com/node-3d/image-raub).

Thank you for the report, I'll try to come up with a solution.

**Comment by raub** [comment] 2018-11-29 11:48
@eard7 Hey, you can try the newest [3d-core-raub](https://github.com/node-3d/3d-core-raub), there is a new [example](https://github.com/node-3d/3d-core-raub/blob/master/examples/three/nonpow2.js) showing non-power-of-2 texture.

Basically you don't have to change any of your code, it just works. But as the feature is experimental it is not yet published to NPM, so it is only available from the repo for now.

When everything settles, I will come back to inform you and finally close this issue.

The most relevant changes are:
https://github.com/node-3d/glfw-raub/blob/master/js/document.js#L124
https://github.com/node-3d/image-raub/blob/master/cpp/image.cpp#L154

**Comment by raub** [comment] 2018-12-06 12:23
Should work correctly since https://github.com/node-3d/3d-core-raub/tree/v1.0.0
`npm i 3d-core-raub@1.0.0`

NOTE: this behavior is not affected by **webgl-raub**. It's just because the issue is posted here.

**Closed as completed by raub** 2018-12-06 12:23 UTC

**Comment by manthan-m2web** [comment] 2021-12-15 09:53
3

**Comment by rohit-choudhary14** [comment] 2023-02-28 06:08
h
